{% set name = "tetgen" %}
{% set version = "1.5.1" %}
{% set sha256 = "e46a4434a3e7c00044c8f4f167e18b6f4a85be7d22838c8f948ce8cc8c01b850" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://wias-berlin.de/software/tetgen/1.5/src/tetgen{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-cmake-install-directive-for-targets.patch

build:
  number: 1000
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >2.8
    - ninja

test:
  commands:
    - test -f ${PREFIX}/bin/tetgen  # [unix]
    - test -f ${PREFIX}/lib/libtet.a  # [unix]
    - test -f ${PREFIX}/include/tetgen.h  # [unix]
    
    - if not exist %LIBRARY_INC%\\tetgen.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\tet.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\tetgen.exe exit 1  # [win]

about:
  home: http://wias-berlin.de/software/tetgen
  license: AGPLv3
  license_file: LICENSE
  summary: 'A Quality Tetrahedral Mesh Generator and a 3D Delaunay Triangulator'

  description: |
    TetGen is a program to generate tetrahedral meshes of any 3D polyhedral
    domains. TetGen generates exact constrained Delaunay tetrahedralizations,
    boundary conforming Delaunay meshes, and Voronoi partitions. 

extra:
  recipe-maintainers:
    - nehaljwani
    - cekees
    - msarahan
