travis:
  secure:
    BINSTAR_TOKEN: hsQjTV+Jy13riwegEwn8ihG6Cg9lZkFrmYHdK4MRLFkZPQbdQ6EZ5HzN54546fyvTU4L32t/XNWwEnQfLQDwvFhQiqlZ6EiDLIVTXSqV5RntPPUHAPyf8TIbngn+HQQ1kTRQeIZKl7fOdBcue/qwLKsfZYpWN4omXiL3Ylpzzj4tIQzyj7AELQegEW0mqtA2nrNBaEUN6r/KZncvcNgEel9Q052Zckxmvu628tsSWtCe84632trupluU+LzoAw6Lsac5CKgYy8eJzhR9nacyCcUkuIEGLxn+th1TmpLiiVFV3A55xbSl4yNOteVS1H46vaRd0zk3jZRJ6s2qfKauCaVhCmBdMqdieXmKbtuBlqEccqFFdFwNBOzlG4njnIQCfwV/sCWM282I3xwLyXIIUvwNi1N7G02wFLj871ExnVhaqErt2WYzXOk+IW72N2ky596JSmiBcOR+D4k6MKrKYBDZMDDgHeZvc6VOgBRGJBAOqx9owXoQZGixJwI9/3jHVKsI2WGoxkN94bI6Gx9pcm7uAwVotBgdIwbnEVAhz8fC1OwEUzwk5jqFNpBwkxwA2dw4IHZ9xGHOB5M7Jn4BZ0eX7+DC8OtEcYKHeBBdq16j6LOPquRVeIK3UvkstOnQ2srA90ytKu0K7LNwLqO0YRplU3fJ3dCaH87LZH6iIk0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
