appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TyYFsUzMGDkuASkYmNBBFsa1pmGWEytEwDsSip3UJeXpx+pJ8Os8Nhh2ySOVgEeMxcGZXhuFKdUSSEk1y3AqFaI8FO92cnC1vbhx6VFLrf1+tIKJSH3McO7784lfnnB1QObR17aymt2DZppio6Rk8bUPvMoDEEsmmiNilYyMVT2erG0MilMj0GBz1urYv7D+z3haF9+hu2KpOJjGuqIKFaejD6kxbfe4XFTlL3lR/opd11hjW0uwgh72OvwVbgBWKTdzk//FVd8XSMeba4/o9+e8WDSnoAFJ7l0NrIFaSPXNsemvaK63wn56cSahwY0fqU9Vh9rzSVX0XKJjVk+mtOKE7PZJ4Wt06TxjpgA0NnH+UqgVn/Y1uDWeeEawpkkNtoVXiT06cj1bCFsEUyBexrQzBWG8GrVhi5lr2fuZOaJcU6JxknWOqIRg1Fg2716i/4Tgq+ufoPBRPoLvM8CqJfvuKPLHKh/JNl3YBMqxgNve2AzTGTQ5SmizkUOv+baCEy5jB97PMdzABB+4iWWgaJ8QqMAwXFEEGUNdbiXLGnfOQuCJSFt5/YUTQbMPenFvhE3x/PJgfn5+QMSW5oXwFVplqoQVXxCLHNLHMRLae1ZStpDxuEHWk3nAD4o/yJ3iLf6oPcYf+vj2+2UWtsgGEudqZOSGy/EKh2tecuTW16I=}
