travis:
  secure:
    BINSTAR_TOKEN: 0ZxqsIvlcurTuFVrKcQuPBhQj9dhk5I86mCksq1jKCNip3PGalBfPYUdEWYbQk/AVyJILQN6lbzSiy2KPkJADL908fdYBc8YT/IESKvXisx+LNeKAtgrAKTQtFj/NmbuCUhtiIoH78UFwbVDXThgKxWXkIhtBVFGws7pgGhtXMN9LAtIjeguBmbjAJvZ3s6veQ8wOF7pfH+GQDtUO5HbAXuK5DQa5jO2QX7yCdC6sZ8Zw9DQMdPpYLBn8rJ5qmQfgY4mgbfysUl5Nh5ZCsC+RSG3pEIXLd3tBEScOtYG1L3+RxXOoz+CPxcGAHB/FyOiXpaY8ZaNZbGo6aHbA/80NfnaNSqjsyLCXgoUKmHFVAqq63zp6DrRxYdFMowXFe+BSAmZuTtEATQuv6aNY28CZClNP8cHSXEvE1yn6dxn5cgy2kOfUmFFk+JsH+1tTRjDKqd0iHq3P0a9OOUFUDRCHd9xVhPoy/3Yi1Ox6dusEMlqDNFcmJL9Uo08kP/Gtj4P7XR8oUZPXH7PPnPRPlDjWofXXQCiTukHVluIGIOUYlAeMBSK8Louu8oS4X4kMhyWDvE1OA+j8BOqlXqic3X6odWMNulEIL55IblXPpFkVXSXKls8FKX+/fSXUlN04EuxVSkLwvPSUvamUpv9f+jemsMXVgq59/ntjx3II1xSuz0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
